Panasonic ACPI depends on INPUT
Panasonic ACPI driver needs to depend on INPUT.
Otherwise it has build errors when CONFIG_INPUT=n:

drivers/built-in.o: In function `acpi_pcc_hotkey_remove':
pcc_acpi.c:(.text+0x25ded): undefined reference to `input_unregister_device'
pcc_acpi.c:(.text+0x25e03): undefined reference to `input_free_device'
drivers/built-in.o: In function `acpi_pcc_hotkey_notify':
pcc_acpi.c:(.text+0x260d5): undefined reference to `input_event'
pcc_acpi.c:(.text+0x260e2): undefined reference to `input_event'
drivers/built-in.o: In function `acpi_pcc_hotkey_add':
pcc_acpi.c:(.text+0x26267): undefined reference to `input_allocate_device'
pcc_acpi.c:(.text+0x26348): undefined reference to `input_register_device'
pcc_acpi.c:(.text+0x26405): undefined reference to `input_unregister_device'
pcc_acpi.c:(.text+0x26423): undefined reference to `input_free_device'
make[1]: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Andi Kleen <ak@linux.intel.com>