V4L/DVB (8801): [PATCH] VIDEO_SH_MOBILE_CEU should depend on HAS_DMA
	Hi Andrew,

On Thu, 14 Aug 2008, Andrew Morton wrote:
> ERROR: "dma_alloc_coherent" [drivers/media/video/videobuf-dma-contig.ko] undefined!
> ERROR: "dma_sync_single_for_cpu" [drivers/media/video/videobuf-dma-contig.ko] undefined!
> ERROR: "dma_free_coherent" [drivers/media/video/videobuf-dma-contig.ko] undefined!

M68k allmodconfig still selects Sun-3, which sets NO_DMA.
I guess you're also seeing this on the other NO_DMA platforms (h8300, m32r,
s390, and PCI-less SPARC)?

Below is a patch.

Shouldn't it also (or instead) depend on SUPERH or some SuperH platform?
Or is this not done to have more compile-coverage?

commit 0d3244d6439c8c31d2a29efd587c7aca9042c8aa ("V4L/DVB (8342):
sh_mobile_ceu_camera: Add SuperH Mobile CEU driver V3") introduced
VIDEO_SH_MOBILE_CEU, which selects VIDEOBUF_DMA_CONTIG. This circumvents the
dependency on HAS_DMA of VIDEOBUF_DMA_CONTIG.

Add a dependency on HAS_DMA to VIDEO_SH_MOBILE_CEU to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Paul Mundt <lethal@linux-sh.org>
Acked-by: Magnus Damm <damm@igel.co.jp>
Signed-off-by: Guennadi Liakhovetski <g.liakhovetski@gmx.de>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>