kmemtrace: fix build breakage in linux/key.h
Impact: fix build

This patch fixes up the following build breakage caused by commit
e251ea2fa52321009940fad02238ef1c369531ae ("rcu: don't include unnecessary
headers, allow kmemtrace w/ tracepoints"):

    CC [M]  fs/cifs/cifs_spnego.o
  In file included from include/keys/user-type.h:15,
                   from fs/cifs/cifs_spnego.c:24:
  include/linux/key.h:128: error: field ‘sem’ has incomplete type
  make[2]: *** [fs/cifs/cifs_spnego.o] Error 1
  make[1]: *** [fs/cifs] Error 2
  make: *** [fs] Error 2

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
LKML-Reference: <1237884886.25315.39.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>