mach-ux500: fix build error due to unknown 'regulator_en' field
Fix below build error:

  CC      arch/arm/mach-ux500/board-mop500-u8500uib.o
arch/arm/mach-ux500/board-mop500-u8500uib.c:35: error: unknown field 'regulator_en' specified in initializer
arch/arm/mach-ux500/board-mop500-u8500uib.c:35: warning: excess elements in struct initializer
arch/arm/mach-ux500/board-mop500-u8500uib.c:35: warning: (near initialization for 'rmi4_i2c_dev_platformdata')
make[1]: *** [arch/arm/mach-ux500/board-mop500-u8500uib.o] Error 1
make: *** [arch/arm/mach-ux500] Error 2

Signed-off-by: Axel Lin <axel.lin@gmail.com>