linux-next: net tree build failure (depca)
On Sat, 2008-09-13 at 08:04 -0700, Randy Dunlap wrote:
> Also this one on i386:
>
> drivers/net/depca.c:404: error: implicit declaration of function 'depca_common_remove'
> drivers/net/depca.c:1602: error: static declaration of 'depca_common_remove' follows non-static declaration
> drivers/net/depca.c:404: error: previous implicit declaration of 'depca_common_remove' was here
> make[2]: *** [drivers/net/depca.o] Error 1
>

I'd already sent a patch for that to those responsible:

From: Harvey Harrison <harvey.harrison@gmail.com>
Subject: [PATCH] net: compile fix depca.c

Adding accessors to the ->driver_data field missed a forward
declaration that is needed to compile.

Caused by:
commit 107aeb9753159da848f066b26557f0aaab900a90
Author: Hannes Reinecke <hare@suse.de>
Date:   Wed Sep 10 14:16:04 2008 +0200

    Driver core: Use dev_get_drvdata() accessors

Otherwise:
drivers/net/depca.c:404:9: error: undefined identifier 'depca_common_remove'
drivers/net/depca.c: In function ‘depca_isa_remove’:
drivers/net/depca.c:404: error: implicit declaration of function ‘depca_common_remove’
drivers/net/depca.c: At top level:
drivers/net/depca.c:1601: error: static declaration of ‘depca_common_remove’ follows non-static declaration
drivers/net/depca.c:404: error: previous implicit declaration of ‘depca_common_remove’ was here

Signed-off-by: Harvey Harrison <harvey.harrison@gmail.com>