ia64: fix build breakage in smp.h
Impact: ia64 build fix

The commit:

 "cpumask: switch over to cpu_online/possible/active/present_mask"

provides a define for cpu_online_map but did not delete the
declaration in arch/ia64/include/asm/smp.h resulting in this
build error:

  CC      arch/ia64/kernel/asm-offsets.s
In file included from include/linux/smp.h:30,
                 from include/linux/sched.h:68,
                 from arch/ia64/kernel/asm-offsets.c:9:
arch/ia64/include/asm/smp.h:60: error: expected ')' before '*' token
arch/ia64/include/asm/smp.h:60: error: expected ')' before 'cpu_online_mask'

Fix: just delete the declaration, it is no longer needed.

Signed-off-by: Tony Luck <tony.luck@intel.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>