linux-next: mfd tree build failure
On Mon, Jan 12, 2009 at 02:03:18PM +1100, Stephen Rothwell wrote:
> Hi Samuel,
>
> Today's linux-next build (x86_64 allmodconfig) failed like this:
>
> ERROR: "__set_irq_handler" [drivers/mfd/pcf50633-core.ko] undefined!
> ERROR: "handle_level_irq" [drivers/mfd/pcf50633-core.ko] undefined!
>
> Immediate cause is clearly commit
> f52046b14b1e1a8a02ae48d0c69d39c5e204644f ("mfd: PCF50633 core driver")
> which introduces this code.  The above functions don't appear to be
> exported to modules.
>
> I have dropped the mfd tree for today.

Oh, sorry about this. I can actually do without this. Here's the patch.
Sameo, can you please apply it ?

    pcf50633: Remove references to non-exported functions

    Remove references to set_irq_type and handle_level_irq which are not
    exported to modules.

    Signed-off-by: Balaji Rao <balajirrao@openmoko.org>