kmemtrace: define tracepoints when CONFIG_TRACEPOINTS is enabled
Impact: fix build

If CONFIG_KMEMTRACE is disabled but CONFIG_TRACEPOINTS is enabled, we need to
define the tracepoints; otherwise linkage fails:

    LD      .tmp_vmlinux1
  arch/x86/kernel/built-in.o: In function `sys_ioperm':
  (.text+0x3743): undefined reference to `__tracepoint_kmalloc'
  arch/x86/kernel/built-in.o: In function `sys_ioperm':
  (.text+0x3784): undefined reference to `__tracepoint_kmalloc'
  arch/x86/kernel/built-in.o: In function `cache_sysfs_init':
  intel_cacheinfo.c:(.cpuinit.text+0x5f3): undefined reference to `__tracepoint_kmalloc'
  intel_cacheinfo.c:(.cpuinit.text+0x768): undefined reference to `__tracepoint_kmalloc'
  arch/x86/mm/built-in.o: In function `reserve_memtype':
  (.text+0x2fb3): undefined reference to `__tracepoint_kmalloc'

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
LKML-Reference: <1237902017.25315.90.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>