sound/pcmcia/vx build error
menuconfig in Sound PCMCIA drivers needs to be tristate so that SND_PCMCIA
can have a value of m so that following drivers can be restricted to m
when needed.

sound/built-in.o: In function `vxpocket_detach':
vxpocket.c:(.text+0x20cfa): undefined reference to `pcmcia_disable_device'
sound/built-in.o: In function `vxpocket_probe':
vxpocket.c:(.text+0x20f46): undefined reference to `pcmcia_request_io'
vxpocket.c:(.text+0x20f5a): undefined reference to `pcmcia_request_irq'
vxpocket.c:(.text+0x20f73): undefined reference to `pcmcia_request_configuration'
vxpocket.c:(.text+0x2101f): undefined reference to `cs_error'
vxpocket.c:(.text+0x21027): undefined reference to `pcmcia_disable_device'
sound/built-in.o: In function `init_vxpocket':
vxpocket.c:(.init.text+0x75b): undefined reference to `pcmcia_register_driver'
sound/built-in.o: In function `exit_vxpocket':
vxpocket.c:(.exit.text+0x28c): undefined reference to `pcmcia_unregister_driver'
make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>