virtio: virtio console can be a module
Today's linux-next build (x86_64 allmodconfig) failed like this:

ERROR: "hvc_alloc" [drivers/char/virtio_console.ko] undefined!
ERROR: "hvc_kick" [drivers/char/virtio_console.ko] undefined!
ERROR: "hvc_poll" [drivers/char/virtio_console.ko] undefined!
ERROR: "hvc_instantiate" [drivers/char/virtio_console.ko] undefined!

So it needs these symbols exported.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
Acked-by: Christian Borntraeger <borntraeger@de.ibm.com>