UBIFS: fix Kconfig
Do the following suggestion from Adrian Bunk:

Please change this and similar other options to:
config UBIFS_FS
	tristate "UBIFS file system support"
	select CRC16
	select CRC32
	select CRYPTO if UBIFS_FS_LZO
	select CRYPTO_LZO if UBIFS_FS_LZO
	depends on MTD_UBI
...
config UBIFS_FS_LZO
	bool "LZO compression support" if UBIFS_FS_ADVANCED_COMPR
	depends on UBIFS_FS
...

This way UBIFS_FS=m, UBIFS_FS_LZO=y will only force CRYPTO_LZO=m and not
CRYPTO_LZO=y.

Also, fix the following error reported by Randy Dunlap:
with:
CONFIG_UBIFS_FS=y
CONFIG_UBIFS_FS_ADVANCED_COMPR=y

build gets:
fs/built-in.o: In function `compr_exit':
compress.c:(.text+0x4a3fc): undefined reference to `crypto_free_tfm'
fs/built-in.o: In function `compr_init':
compress.c:(.init.text+0x11d4): undefined reference to `crypto_alloc_base'
make[1]: *** [.tmp_vmlinux1] Error 1

because CRYPTO is not enabled.

Signed-off-by: Artem Bityutskiy <Artem.Bityutskiy@nokia.com>