kmemtrace: fix build breakage in lib/decompress_bunzip2.c
Impact: fix build

This patch fixes up the following build breakage caused by commit
e251ea2fa52321009940fad02238ef1c369531ae ("rcu: don't include
unnecessary headers, allow kmemtrace w/ tracepoints"):

    CC      lib/decompress_bunzip2.o
  lib/decompress_bunzip2.c: In function ‘start_bunzip’:
  lib/decompress_bunzip2.c:636: error: implicit declaration of function ‘kmalloc’
  lib/decompress_bunzip2.c:636: warning: assignment makes pointer from integer without a cast
  lib/decompress_bunzip2.c: In function ‘bunzip2’:
  lib/decompress_bunzip2.c:682: warning: assignment makes pointer from integer without a cast
  lib/decompress_bunzip2.c:693: warning: assignment makes pointer from integer without a cast
  lib/decompress_bunzip2.c:726: error: implicit declaration of function ‘kfree’
  make[1]: *** [lib/decompress_bunzip2.o] Error 1
  make: *** [lib/] Error 2

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
LKML-Reference: <1237886032.25315.48.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>