kmemtrace: fix build breakage in lib/decompress_inflate.c
Impact: fix build

This patch fixes up the following build breakage caused by commit
e251ea2fa52321009940fad02238ef1c369531ae ("rcu: don't include
unnecessary headers, allow kmemtrace w/ tracepoints"):

    CC      lib/decompress_inflate.o
  lib/decompress_inflate.c: In function ‘gunzip’:
  lib/decompress_inflate.c:45: error: implicit declaration of function ‘kmalloc’
  lib/decompress_inflate.c:45: warning: assignment makes pointer from integer without a cast
  lib/decompress_inflate.c:57: warning: assignment makes pointer from integer without a cast
  lib/decompress_inflate.c:65: warning: assignment makes pointer from integer without a cast
  lib/decompress_inflate.c:71: warning: assignment makes pointer from integer without a cast
  lib/decompress_inflate.c:154: error: implicit declaration of function ‘kfree’
  make[1]: *** [lib/decompress_inflate.o] Error 1
  make: *** [lib/] Error 2

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
LKML-Reference: <1237886030.25315.47.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>