kmemtrace: fix build brekage in linux/fs.h
Impact: build fix

This patch fixes up the following build breakage caused by commit
e251ea2fa52321009940fad02238ef1c369531ae ("rcu: don't include
unnecessary headers, allow kmemtrace w/ tracepoints").

    CC      init/do_mounts_initrd.o
  In file included from init/do_mounts_initrd.c:3:
  include/linux/fs.h: In function ‘alloc_secdata’:
  include/linux/fs.h:2237: error: implicit declaration of function ‘get_zeroed_page’
  include/linux/fs.h:2237: error: ‘GFP_KERNEL’ undeclared (first use in this function)
  include/linux/fs.h:2237: error: (Each undeclared identifier is reported only once
  include/linux/fs.h:2237: error: for each function it appears in.)
  include/linux/fs.h: In function ‘free_secdata’:
  include/linux/fs.h:2242: error: implicit declaration of function ‘free_page’
  In file included from include/linux/slab.h:12,
                   from include/linux/percpu.h:5,
                   from include/linux/percpu_counter.h:13,
                   from include/linux/ext2_fs_sb.h:20,
                   from include/linux/ext2_fs.h:69,
                   from init/do_mounts_initrd.c:5:
  include/linux/gfp.h: At top level:
  include/linux/gfp.h:223: error: conflicting types for ‘get_zeroed_page’
  include/linux/fs.h:2237: error: previous implicit declaration of ‘get_zeroed_page’ was here
  make[1]: *** [init/do_mounts_initrd.o] Error 1
  make: *** [init] Error 2

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
LKML-Reference: <1237882472.25315.32.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>