linux-next: 3c509 build fix
Hi Adrian,

Adrian Bunk wrote:
> On Sun, Sep 14, 2008 at 02:17:57PM -0700, Randy Dunlap wrote:
>> drivers/net/3c509.c fails (CONFIG_PM=y) with:
>>
>> drivers/built-in.o:(.data+0x7dcc): undefined reference to `el3_resume'
>> drivers/built-in.o:(.data+0x7e08): undefined reference to `el3_resume'
>>
>> It seems that this function does not exist in the source file.
>
>
> It got removed by:
>
>
> commit 107aeb9753159da848f066b26557f0aaab900a90
> Author: Hannes Reinecke <hare@suse.de>
> Date:   Wed Sep 10 14:16:04 2008 +0200
>
>     Driver core: Use dev_get_drvdata() accessors
>
>     Deprecated direct access to the ->driver_data field and
>     use accessors throughout.
>
>     Signed-off-by: Hannes Reinecke <hare@suse.de>
>     Cc: Kay Sievers <kay.sievers@vrfy.org>
>     Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>
>
Sorry. Here it is again.

Cheers,

Hannes
--
Dr. Hannes Reinecke		      zSeries & Storage
hare@suse.de			      +49 911 74053 688
SUSE LINUX Products GmbH, Maxfeldstr. 5, 90409 Nürnberg
GF: Markus Rex, HRB 16746 (AG Nürnberg)

Re-add el3_resume to 3c509

In commit 107aeb9753159da848f066b26557f0aaab900a90
el3_resume() from drivers/net/3c509.c accidentally got
removed. Re-add it.

Signed-off-by: Hannes Reinecke <hare@suse.de>