build failure with netfilter on __nf_ct_helper_find()
Hi Stephen,

The next-20080521 kernel build fails, on x86_64 machine

CC net/netfilter/nf_conntrack_helper.o
net/netfilter/nf_conntrack_helper.c: In function ‘__nf_ct_helper_find’:
net/netfilter/nf_conntrack_helper.c:58: error: implicit declaration of function ‘hlist_for_each_entry_rcu’
net/netfilter/nf_conntrack_helper.c:58: error: ‘hnode’ undeclared (first use in this function)
net/netfilter/nf_conntrack_helper.c:58: error: (Each undeclared identifier is reported only once
net/netfilter/nf_conntrack_helper.c:58: error: for each function it appears in.)
net/netfilter/nf_conntrack_helper.c:58: error: expected ‘;’ before ‘{’ token
net/netfilter/nf_conntrack_helper.c:50: warning: unused variable ‘mask’
net/netfilter/nf_conntrack_helper.c: In function ‘__nf_conntrack_helper_find_byname’:
net/netfilter/nf_conntrack_helper.c:74: error: ‘hnode’ undeclared (first use in this function)
net/netfilter/nf_conntrack_helper.c:74: error: expected ‘;’ before ‘{’ token
net/netfilter/nf_conntrack_helper.c: In function ‘nf_conntrack_helper_register’:
net/netfilter/nf_conntrack_helper.c:117: error: implicit declaration of function ‘hlist_add_head_rcu’
net/netfilter/nf_conntrack_helper.c: In function ‘nf_conntrack_helper_unregister’:
net/netfilter/nf_conntrack_helper.c:133: error: implicit declaration of function ‘hlist_del_rcu’
make[2]: *** [net/netfilter/nf_conntrack_helper.o] Error 1
make[1]: *** [net/netfilter] Error 2
make: *** [net] Error 2

This build error is because of the missing include file.I have tested
the patch for the build failure only.

Signed-off-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>
--