kmemtrace: avoid cyclic header dependency in linux/rcutree.h
Impact: fix build

Commit e251ea2fa52321009940fad02238ef1c369531ae ("rcu: don't include
unnecessary headers, allow kmemtrace w/ tracepoints") forgot to remove the
cyclic header dependency in linux/rcutree.h which causes the following build
failure:

    CC      arch/x86/kernel/asm-offsets.s
  In file included from include/linux/slub_def.h:13,
                   from include/linux/slab.h:153,
                   from include/linux/percpu.h:5,
                   from include/linux/rcutree.h:36,
                   from include/linux/rcupdate.h:60,
                   from include/linux/tracepoint.h:18,
                   from include/linux/module.h:19,
                   from include/linux/crypto.h:21,
                   from arch/x86/kernel/asm-offsets_32.c:7,
                   from arch/x86/kernel/asm-offsets.c:2:
  include/trace/kmemtrace.h:24: error: expected ‘)’ before ‘(’ token
  include/trace/kmemtrace.h:31: error: expected ‘)’ before ‘(’ token
  include/trace/kmemtrace.h:38: error: expected ‘)’ before ‘(’ token
  include/trace/kmemtrace.h:46: error: expected ‘)’ before ‘(’ token
  include/trace/kmemtrace.h:54: error: expected ‘)’ before ‘(’ token
  include/trace/kmemtrace.h:57: error: expected ‘)’ before ‘(’ token
  In file included from include/linux/slab.h:153,
                   from include/linux/percpu.h:5,
                   from include/linux/rcutree.h:36,
                   from include/linux/rcupdate.h:60,
                   from include/linux/tracepoint.h:18,
                   from include/linux/module.h:19,
                   from include/linux/crypto.h:21,
                   from arch/x86/kernel/asm-offsets_32.c:7,
                   from arch/x86/kernel/asm-offsets.c:2:
  include/linux/slub_def.h: In function ‘kmalloc_large’:
  include/linux/slub_def.h:236: error: implicit declaration of function ‘trace_kmalloc’
  make[1]: *** [arch/x86/kernel/asm-offsets.s] Error 1
  make: *** [prepare0] Error 2

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
Cc: paulmck@linux.vnet.ibm.com
LKML-Reference: <1237898630.25315.83.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>