kmemtrace: fix build breakage in befs
Impact: build fix

This patch fixes up the following build breakage caused by commit
e251ea2fa52321009940fad02238ef1c369531ae ("rcu: don't include
unnecessary headers, allow kmemtrace w/ tracepoints"):

    CC      fs/befs/debug.o
  fs/befs/debug.c: In function ‘befs_error’:
  fs/befs/debug.c:31: error: implicit declaration of function ‘kmalloc’
  fs/befs/debug.c:31: warning: initialization makes pointer from integer without a cast
  fs/befs/debug.c:42: error: implicit declaration of function ‘kfree’
  fs/befs/debug.c: In function ‘befs_warning’:
  fs/befs/debug.c:49: warning: initialization makes pointer from integer without a cast
  fs/befs/debug.c: In function ‘befs_debug’:
  fs/befs/debug.c:73: warning: assignment makes pointer from integer without a cast
  make[1]: *** [fs/befs/debug.o] Error 1
  make: *** [fs/befs/] Error 2

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
LKML-Reference: <1237884230.25315.33.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>