Fix page_cgroup build breakage
On s390 I get this:

  CC      mm/page_cgroup.o
mm/page_cgroup.c: In function 'init_section_page_cgroup':
mm/page_cgroup.c:111: error: implicit declaration of function 'vmalloc_node'
mm/page_cgroup.c:111: warning: assignment makes pointer from integer without a cast
mm/page_cgroup.c: In function '__free_page_cgroup':
mm/page_cgroup.c:140: error: implicit declaration of function 'vfree'
make[1]: *** [mm/page_cgroup.o] Error 1
make: *** [mm] Error 2

caused by 52d4b9ac0b985168009c2a57098324e67bae171f
("memcg: allocate all page_cgroup at boot")

Cc: KAMEZAWA Hiroyuki <kamezawa.hiroyu@jp.fujitsu.com>
Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>