m68k_zorro_fix
On Thu, May 15, 2008 at 07:04:47AM +1000, Tony Breeds wrote:
> On Wed, May 14, 2008 at 01:50:08PM -0700, Randy Dunlap wrote:
>
> > Ugh.  Can you please make the log file more readable?
> >
> > Or is a problem with my browser (firefox)?
>
> It's a raw download, save it as a file and then view it (or look at the
> source).

FWIW the error in question is:
  Using /scratch1/tony/next as source for kernel
  GEN     /scratch1/tony/next_out/Makefile
  CHK     include/linux/version.h
  CHK     include/linux/utsrelease.h
  CALL    /scratch1/tony/next/scripts/checksyscalls.sh
  CHK     include/linux/compile.h
  CC [M]  drivers/net/zorro8390.o
In file included from /scratch1/tony/next/drivers/net/zorro8390.c:47:
/scratch1/tony/next/drivers/net/lib8390.c: In function 'ei_tx_err':
/scratch1/tony/next/drivers/net/lib8390.c:556: error: 'ei_local' undeclared (first use in this function)
/scratch1/tony/next/drivers/net/lib8390.c:556: error: (Each undeclared identifier is reported only once
/scratch1/tony/next/drivers/net/lib8390.c:556: error: for each function it appears in.)
/scratch1/tony/next/drivers/net/lib8390.c: In function 'ei_rx_overrun':
/scratch1/tony/next/drivers/net/lib8390.c:823: error: 'ei_local' undeclared (first use in this function)
make[3]: *** [drivers/net/zorro8390.o] Error 1
make[2]: *** [drivers/net] Error 2
make[1]: *** [drivers] Error 2
make: *** [sub-make] Error 2

It was introduced by 3f8cb098859bbea29d7b3765a3102e4a6bf81b85
(drivers/net/lib8390: fix warning, trim trailing whitespace)

The problem is that ei_inb_p() is using various #defines (from
drivers/net/8390.h) that use EI_SHIFT, which in the zorro8390 case uses
ei_local.  Since zorro8390 is only build for m68k, guard the definition of
ei_local with CONFIG_M68K

The patch below fixes the zorro8390 build, and I think will keep the warnings
that Jeff is trying to silence silenced.

Signed-off-by: Tony Breeds <tony@bakeyournoodle.com>