fix IXGBE dependencies
ixgbe needs to be restricted to the same build config (m/y)
as DCA since it calls the dca_*() functions.

ixgbe_main.c:(.text+0xd9c09): undefined reference to `dca3_get_tag'
ixgbe_main.c:(.text+0xd9cc9): undefined reference to `dca3_get_tag'
ixgbe_main.c:(.text+0xda5c1): undefined reference to `dca_add_requester'
ixgbe_main.c:(.text+0xda5d6): undefined reference to `dca_remove_requester'
text+0xdc162): undefined reference to `dca_add_requester'
text+0xdc1d3): undefined reference to `dca_remove_requester'
ixgbe_main.c:(.init.text+0xa74b): undefined reference to `dca_register_notify'
ixgbe_main.c:(.devinit.text+0xa4ca): undefined reference to `dca_add_requester'
ixgbe_main.c:(.exit.text+0xd21): undefined reference to `dca_unregister_notify'
ixgbe_main.c:(.devexit.text+0x72d): undefined reference to `dca_remove_requester'
make[1]: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>