uwb: fix Kconfig causing undefined references
Fix UWB kconfig so that function reference problems are not generated.

next-20080430/drivers/uwb/whc-rc.c:478: undefined reference to `hwarc_filter_event'
next-20080430/drivers/uwb/whc-rc.c:478: undefined reference to `hwarc_filter_cmd'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>