irnet_irda.c must #include <asm/unaligned.h>
This patch fixes the following compile error caused by
commit 332223831e86b2e17b48b4afafad07d8e3b73861
(irda: Fix a misalign access issue. (v2)):

<--  snip  -->

...
  CC      net/irda/irnet/irnet_irda.o
/home/bunk/linux/kernel-2.6/git/linux-2.6/net/irda/irnet/irnet_irda.c: In function ‘irnet_discovery_indication’:
/home/bunk/linux/kernel-2.6/git/linux-2.6/net/irda/irnet/irnet_irda.c:1676: error: implicit declaration of function ‘get_unaligned’
make[4]: *** [net/irda/irnet/irnet_irda.o] Error 1

<--  snip  -->

Reported-by: Adrian Bunk <bunk@kernel.org>
Signed-off-by: Adrian Bunk <bunk@kernel.org>