ia64: fix build bug
ia64 allmodconfig:

arch/ia64/kernel/iosapic.c: In function `get_target_cpu':
arch/ia64/kernel/iosapic.c:723: error: `nr_cpus_ids' undeclared (first use in this function)
arch/ia64/kernel/iosapic.c:723: error: (Each undeclared identifier is reported only once
arch/ia64/kernel/iosapic.c:723: error: for each function it appears in.)

- someone can't type (or test)

- nr_cpu_ids is declared in cpumask.h.  Include it.

Signed-off-by: Ingo Molnar <mingo@elte.hu>