s390: fix compile error due to smp_call_function
the following patch in linux-next (v2.6.26-rc9-7220-g5e36ed1)

commit 8691e5a8f691cc2a4fda0651e8d307aaba0e7d68
Author: Jens Axboe <jens.axboe@oracle.com>
Date:   Fri Jun 6 11:18:06 2008 +0200
smp_call_function: get rid of the unused nonatomic/retry argument

causes a build error on s390.
  CC      arch/s390/kernel/time.o
arch/s390/kernel/time.c: In function 'stp_work_fn':
arch/s390/kernel/time.c:1448: error: too many arguments to function 'smp_call_function'
arch/s390/kernel/time.c:1481: error: too many arguments to function 'smp_call_function'

The fix is simple and obvious, remove the unneeded argument.

Signed-off-by: Christian Borntraeger <borntraeger@de.ibm.com>