xfs fix 1
Timothy Shimmin wrote:
>>> 2. ACL's undefined
>>>
>>>   CC      fs/xfs/linux-2.6/xfs_xattr.o
>>> /local/linsrc/linux-next-20080624/fs/xfs/linux-2.6/xfs_xattr.c: In function 'xfs_decode_acl':
>>> /local/linsrc/linux-next-20080624/fs/xfs/linux-2.6/xfs_xattr.c:40: error: '_ACL_TYPE_ACCESS' undeclared (first use in this function)
>>> /local/linsrc/linux-next-20080624/fs/xfs/linux-2.6/xfs_xattr.c:40: error: (Each undeclared identifier is reported only once
>>> /local/linsrc/linux-next-20080624/fs/xfs/linux-2.6/xfs_xattr.c:40: error: for each function it appears in.)
>>> /local/linsrc/linux-next-20080624/fs/xfs/linux-2.6/xfs_xattr.c:42: error: '_ACL_TYPE_DEFAULT' undeclared (first use in this function)
>>> make[3]: *** [fs/xfs/linux-2.6/xfs_xattr.o] Error 1
>> And this will be a !CONFIG_XFS_POSIX_ACL build, I think.
>>
> Yep. I didn't test the hch patch without CONFIG_XFS_POSIX_ACL. Oops.
>
> xfs_acl.h:
>
> #ifdef CONFIG_XFS_POSIX_ACL
> ...
> #define _ACL_TYPE_ACCESS        1
> #define _ACL_TYPE_DEFAULT       2
> ...
> #endif
>
> There is a bunch of ACL code in linux-2.6/xfs_xattr.c.
> Possibly we could just modify xfs_acl.h as I think most other calls
> have the non CONFIG'ed versions.
> I'll have a look.
>

So we could move up the acl defines in xfs_acl.h.
Unless Christoph wants some other rearrangement...