ldp-fix-1
> This is still a problem for s390 all{mod,yes}config as of yesterday:
>
> drivers/misc/aectc/aec_tc.c:75: error: implicit declaration of function 'ioread8'

Oops.  We probably need depends on PCI.

Signed-off-by: Brandon Philips <bphilips@suse.de>