UBIFS: making ubifs compile with gcc-3.4
ubifs fails to compile with my gcc 3.4.4 (for arm), bombing with:

fs/built-in.o: In function `ubifs_create_dflt_lpt':
lpt_commit.c:(.text+0x88690): undefined reference to `__you_cannot_kmalloc_that_much'
make[1]: *** [.tmp_vmlinux1] Error 1

It compiles with 4.1.2 ok though. Some web searches suggest that this is
due to a compiler bug. Patches have been applied in other parts of the
tree to work around this so perhaps you'll consider this patch for ubifs
also.

I found that rearranging the kmalloc order makes it compile. I don't
believe there is any effect on the behaviour.

Signed-off-by: Hamish Moffatt <hamish@cloud.net.au>
Signed-off-by: Artem Bityutskiy <Artem.Bityutskiy@nokia.com>