linux-next: generic helpers for arch IPI function calls build bug / s390
Jens,

you forgot to remove #include <linux/spinlock.h> from linux/smp.h while
fixing the original s390 build bug.

Patch below fixes this build bug caused by header inclusion dependencies:

  CC      kernel/timer.o
In file included from include/linux/spinlock.h:87,
                 from include/linux/smp.h:11,
                 from include/linux/kernel_stat.h:4,
                 from kernel/timer.c:22:
include/asm/spinlock.h: In function '__raw_spin_lock':
include/asm/spinlock.h:69: error: implicit declaration of function 'smp_processor_id'

Please merge the patch below with

"Add generic helpers for arch IPI function calls"

Thanks.

Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>